### ISSUE TITLE
Put package.json back to top-level and add dockerignore

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#42]
doubidou

**Comment by vallettea** [comment]
why ?

**Comment by DavidBruant** [comment]
`package.json` is a project-level thing. That's how we've been doing things on other projects (except a private one which mixed different technologies).
The question is rather why isn't it the case?
@iOiurson told me it was related to not copying user_research files to docker containers, but that problem is better solved by a dockerignore file.

**Comment by vallettea** [comment]
this is because we use to have pure nodejs projects but 6element is not a node project anymore (there are docs from roxane, materials about sensors (one day), apps...). Only one part of this repos is a node project.
Moreover, i find it cleaner to have at the root what you need to deploy + readme and in each subdirectory a piece of the whole project.

**Comment by DavidBruant** [comment]
Then the compose-dev/prod should be moved to the app directory, no? Or should the database directory go down?
I'm fine with anything, but there is something off with the current situation.

**Comment by DavidBruant** [comment]
After discussion, repurposing the issue:
* Moving "web" dockerfile to /app directory. There is a [compose option to specify the dockerfile](https://docs.docker.com/compose/yml/#dockerfile), so the compose files can stay at the root.
* In the dockerfile, `package.json` is copied to /6element/app, not just 6element (to keep things together in the container, current situation is backwards).
