### ISSUE TITLE
When no response, the admin should try to reboot the sensor

### ISSUE THREAD

**Issue by vallettea** [anthill/6element#94]

**Comment by DavidBruant** [comment]
I would advise against doing this.
"When no response" is and can only be vague. This means the admin may reboot sensors sporadically.
IMHO, rebooting sensors should always be a manual and explicit action. With whatever definition of "When no response", we should probably only inform the user via the admin UI and offer a button to reboot the sensor.

If we really want to take the automated road, we should at least 
* inform the user of what is about to happen
* offer the option to cancel (maybe for 10secs)
* use the [page visibility API](https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API) so it never happens when the user is not looking at the screen.
